#!/bin/sh /etc/rc.common
# Copyright (C) 2017,2018 BG5HHP

START=99
SERVICE_USE_PID=0

PKG_NAME=MMDVMHost
BIN_FILE=/usr/sbin/MMDVMHost
CONF_FILE=/etc/MMDVM.ini
PID_FILE=/tmp/MMDVMHost.pid

do_start() {
  if [ -e ${CONF_FILE} ]; then
    echo "Starting..."
    ${BIN_FILE} ${CONF_FILE}
    sleep 5
    local PID=`pidof ${PKG_NAME}`
    if [ $? -eq 1 ]; then
        echo "Process is not found, ${PKG_NAME} will not start."
        return 1
    fi
    echo ${PID} >${PID_FILE}
    >&2 echo "${PKG_NAME} started"
  else
    >&2 echo "$CONF_FILE is missing, ${PKG_NAME} will not start."
    return 1
  fi
  return 0
}

start() {
  do_start
}

stop() {
  if [ -e ${PID_FILE} ]; then
    local PID=`cat ${PID_FILE}`
    kill $PID > /dev/null 2>&1
    rm -f ${PID_FILE}
    echo "${PKG_NAME} stopped"
  else
    echo "${PKG_NAME} is not running"
  fi
  return 0
}

restart() {
  stop
  start
}
