#!/bin/sh /etc/rc.common
# Copyright (C) 2017,2018 BG5HHP

START=99
SERVICE_USE_PID=0

PKG_NAME=P25Reflector
BIN_FILE=/usr/sbin/P25Reflector
CONF_FILE=/etc/P25Reflector.ini
PID_FILE=/tmp/P25Reflector.pid


do_start() {
  if [ -e ${CONF_FILE} ]; then
    echo "Starting..."
    ${BIN_FILE} ${CONF_FILE}
    sleep 3
    PID=`pidof ${PKG_NAME}`
    if [ $? -eq 1 ]; then
        echo "Process does not exist, ${PKG_NAME} will not start."
        return 1
    fi
    echo ${PID} >${PID_FILE}
    >&2 echo "${PKG_NAME} started"
  else
    >&2 echo "configuration file missing, ${PKG_NAME} will not start."
    return 1
  fi
  return 0
}

start() {
  do_start
}

stop() {
	if [ -e ${PID_FILE} ]; then
		PID=`cat ${PID_FILE}`
		kill $PID > /dev/null 2>&1
		rm -f ${PID_FILE}
		echo "${PKG_NAME} stopped"
	else
		echo "${PKG_NAME} is not running"
	fi
    return 0
}

restart() {
	stop
	start
}
